version: '3'
services:

    proxy:
        image: nginx:1.16
        environment:
            - TZ="UTC"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./service-configuration/nginx/proxy/conf.d/reverse_proxy.conf:/etc/nginx/conf.d/reverse_proxy.conf:ro
            - ./service-configuration/nginx/proxy/htpasswd:/etc/nginx/htpasswd:ro
            - ./service-configuration/nginx/ssl:/etc/nginx/ssl:ro
        depends_on:
            - nextcloud-www
        networks:
            - example-net
        logging:
            driver: journald
            options:
                labels: "application"
                tag: "nginx|{{.ImageName}}|{{.DaemonName}}"
        labels:
            application: "reverse_proxy"
        restart: always

    nextcloud-www:
        image: nginx:1.16
        environment:
            - TZ="UTC"
        volumes:
            - ./service-configuration/nginx/nextcloud/conf.d/nextcloud.conf:/etc/nginx/conf.d/nextcloud.conf:ro
            - ./service-configuration/nginx/nextcloud/nginx.conf:/etc/nginx/nginx.conf:ro
            - /srv/www/www_nextcloud:/var/www
        depends_on:
            - nextcloud-php
        networks:
            - example-net
        logging:
            driver: journald
            options:
                labels: "application"
                tag: "nginx|{{.ImageName}}|{{.DaemonName}}"
        labels:
            application: "nextcloud_private"
        restart: always

    nextcloud-php:
        image: php:7.2-fpm
        environment:
            - TZ="UTC"
        volumes:
            - /srv/www/www_nextcloud:/var/www
        networks:
            - example-net
        logging:
            driver: journald
            options:
                labels: "application"
                tag: "php|{{.ImageName}}|{{.DaemonName}}"
        labels:
            application: "nextcloud_private"
        restart: always

    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.2.0"
        hostname: elasticsearch
        ports:
            - "9200:9200"
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - TZ=UTC
            - "discovery.type=single-node"
        volumes:
            - "./volumes/elasticsearch:/usr/share/elasticsearch/data"
            - "./service-configuration/elk/es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
        ulimits:
            memlock:
              soft: -1
              hard: -1
        networks:
            example-net:
                ipv4_address: 172.20.0.40
        logging:
            driver: journald
            options:
                labels: "application"
                tag: "elasticsearch|{{.ImageName}}|{{.DaemonName}}"
        labels:
            application: "elastic"
        restart: always

    kibana:
        image: "docker.elastic.co/kibana/kibana:7.2.0"
        hostname: kibana
        ports:
            - "5601:5601"
        environment:
            - TZ=UTC
        volumes:
            - "./service-configuration/elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml"
        networks:
            - example-net
        logging:
            driver: journald
            options:
                labels: "application"
                tag: "kibana|{{.ImageName}}|{{.DaemonName}}"
        labels:
            application: "kibana"
        restart: always

networks:
    example-net:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: br-docker-0
        ipam:
            config:
                - subnet: 172.20.0.0/16
